Add notes features
zombre98/music-neural-network pull request #9
Opened 2020-07-10 18:09 UTC by antoinelefebvre17

2020-07-11 16:43 UTC, zombre98 requested changes
What's with all the .pyc files?
Can you remove it please

2020-07-11 22:00 UTC, antoinelefebvre17 commented
> What's with all the .pyc files?
> Can you remove it please

Done

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +        print("Data recovery...")
Could we add a `verbose` option which defaults to `False` ?

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +            currentTime = tick2second(msg.time, self.mid.ticks_per_beat, tempoTemp) + currentTime
Minor comment, why don't you use the `+=` operator ?

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +                        {'tempo': round(tempo2bpm(msg.tempo)), 'repetition': 1, 'time': tick2second(msg.time, self.mid.ticks_per_beat, msg.tempo)})
Should this go inside the `Tempos` class ?
The class would directly have a method `append` that receives the tempo `msg` and` currentTime` and does this job of finding the repetitions, etc..

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +                    self.notes.notesWithRepetition.append({'note': msg.note, 'repetition': 1})
Same for this part, maybe move the logic to the `Notes` class

2020-07-12 20:38 UTC, armandmgt commented on app/features/Type/Notes.py
> +    def setTime(self, time):
Maybe rename to `totalTime` ?

2020-07-12 20:38 UTC, armandmgt commented on app/features/Type/Notes.py
> +        self.notesWithRepetition = []  # {'tempo': , 'repetition': , 'time': }
Uh oh, `tempos` in the `Notes` class ?

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +                        self.notes.notesWithRepetition[j]['repetition'] = self.notes.notesWithRepetition[j][
`+= 1`

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +                        self.tempos.temposWithRepetition[j]['repetition'] = self.tempos.temposWithRepetition[j][
`+= 1`

2020-07-12 20:38 UTC, armandmgt commented on app/features/MidiData.py
> +                        self.tempos.temposWithRepetition[j]['time'] = tick2second(msg.time, self.mid.ticks_per_beat, msg.tempo) + self.tempos.temposWithRepetition[j]['time']
`+= tick2second(...)`

2020-07-15 07:48 UTC, armandmgt approved these changes
👌

2020-07-16 12:10 UTC, zombre98 approved these changes

2020-07-17 09:01 UTC, merged